name: Check All

on:
  pull_request:
    branches: [main]
  push:
    branches: ['*']

jobs:
  check-all:
    runs-on: ubuntu-latest
    env:
      PUBLIC_SANITY_PROJECT_ID: ${{ vars.PUBLIC_SANITY_PROJECT_ID }}
      PUBLIC_SANITY_DATASET: ${{ vars.PUBLIC_SANITY_DATASET }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
      - run: npm ci
      - run: npm run check:all
